sshfiles/overview/views.py
import os
import json
import fcntl
from flask import Blueprint, render_template, request
from sshfiles.util import indexing

overview_blueprint = Blueprint('overview', __name__, static_folder='static',
                               static_url_path='/overview/static',
                               template_folder='templates')


@overview_blueprint.route('/', methods=['GET'])
def overview_get():
    """Show the overview page."""
    # kvargs for render_template
    args = {}
    # Attempt reading settings
    if os.path.isfile('config.json'):
        with open('config.json', 'r') as f:
            fcntl.flock(f, fcntl.LOCK_EX)
            args['conf'] = json.load(f)
    # Attempt reading file index
    if os.path.isfile('index.json'):
        with open('index.json', 'r') as f:
            fcntl.flock(f, fcntl.LOCK_EX)
            args['files'] = json.load(f)
            indexing.make_urls(
                args['files'], args['conf']['username'], args['conf']['ip']
            )
    return render_template('overview.html', **args)


@overview_blueprint.route('/', methods=['POST'])
def overview_post():
    """Update the file index."""
    # Get settings
    conf = {}
    conf['path'] = request.form['path']
    conf['username'] = request.form['username']
    conf['ip'] = request.form['ip']
    # Save the potentially updated configuration
    with open('config.json', 'w') as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        json.dump(conf, f)
    # Get videos
    videos = indexing.get_videos(conf['path'])
    # Dump video index for later use
    with open('index.json', 'w') as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        json.dump(videos, f)
    indexing.make_urls(videos, conf['username'], conf['ip'])
    return render_template('overview.html', conf=conf, files=videos)

sshfiles/overview/templates/overview.html
<!DOCTYPE html>
<html>
    <head>
        <title>File index</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('overview.static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='material.min.css') }}">
        <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    </head>
    <body>
        <div class="mdl-card mdl-shadow--4dp card-centered">
            <div class="mdl-card__supporting-text">
                You only need to update the index when files have changed. This can take several seconds.
                <form action="{{ url_for('overview.overview_post') }}" method="POST">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label{% if conf %} is-dirty{% endif %}">
                        <input class="mdl-textfield__input" type="text" id="path" name="path" required{% if conf %} value="{{ conf.path }}"{% endif %}>
                        <label class="mdl-textfield__label" for="path">Path</label>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label{% if conf %} is-dirty{% endif %}">
                        <input class="mdl-textfield__input" type="text" id="username" name="username" required{% if conf %} value="{{ conf.username }}"{% endif %}>
                        <label class="mdl-textfield__label" for="username">Username (for SSH)</label>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label{% if conf %} is-dirty{% endif %}">
                        <input class="mdl-textfield__input" type="text" id="ip" name="ip" required{% if conf %} value="{{ conf.ip }}"{% endif %}>
                        <label class="mdl-textfield__label" for="username">IP address (for SSH)</label>
                    </div>
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" type="submit">
                    Update index
                    </button>
                </form>
            </div>
        </div>
        {%- if files is defined %}
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric">Filename</th>
                </tr>
            </thead>
            <tbody>
                {%- for row in files %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric"><a class="clicker" data-clipboard-text="{{ row[1] }}" href="javascript:void(0)">{{ row[0] }}</a></td>
                </tr>
                {%- endfor %}
            </tbody>
        </table>
        {%- endif %}
        <script src="{{ url_for('static', filename='material.min.js') }}"></script>
        <script src="{{ url_for('static', filename='clipboard.min.js') }}"></script>
        <script>
        new Clipboard('.clicker');
        </script>
    </body>
</html>